---
abstract: 'A Perl interface to the Tumblr web API'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Tumblr
requires:
  Any::Moose: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  Try::Tiny: 0
  URI: 0
  URI::PathAbstract: 0
version: 0.0010
